reading_task:
  description: >
    Extract the entire provided text.
    Return the raw text contents without modification
  expected_output: >
    The complete extracted text of the PDF document
  agent: pdf_reader

summarize_task:
  description: >
    Take the provided PDF text and summarize into a concise overview that highlights the main points
  expected_output: >
    A concise summary (2-4 paragraphs) highlighting the key themes and facts from the document
  agent: summarizer
  context:
    - reading_task
  output_file:
    summary.md

create_quiz_task:
  description: >
    Using the summary fo the PDF's content, create a quiz with multiple-choice questions that test understanding
    of the main concepts. Provide 5, multiple-choice questions. Each question should have 4 options and indicate 
    the correct answer.
  expected_output: >
    a quiz with 5 multiple choice questions and their correct answers
  agent: quiz_maker
  context:
    - summarize_task
  output_file:
    quiz.md

user_test_task:
  description: >
    Present the quiz questions to the user. Ask them to provide their answers.
    Check the correctness of each user response and provide a final score.
  expected_output: >
    A summary of user performance, e.g. "You answered x out of y questions correctly."
  agent: quiz_buddy
  context:
    - create_quiz_task
  human_input: true
